version: '3.7'
services:
  db:
    container_name: food-tracker
    build: .
    restart: unless-stopped
    ports:
      - '5435:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local