export enum IconNames {
	Close = 'Close',
	Record = 'Record',
	Trash = 'Trash',
	ChevronCircle = 'ChevronCircle',
	Pencil = 'Pencil',
    Logs = 'Logs',
	Mic = 'Mic',
	Plus = 'Plus',
	ChevronUp = 'ChevronUp',
	ChevronDown = 'ChevronDown',
	ChevronRight = 'ChevronRight',
	ChevronLeft = 'ChevronLeft',
	RobotHead = 'RobotHead',
	CheckMark = 'CheckMark',
	Template = 'Template',
	Menu = 'Menu',
	LogOut = 'LogOut',
	Settings = 'Settings',
    Metrics = 'Metrics',
	LoadingDots = 'LoadingDots', // Only used for loading animation
}
